
## Fast.BI Deployment 
# Helm deployment values for Service.
# Helm Chart name: {{ chart_name }}
# Helm Chart repo: {{ chart_repo }}
# Helm Chart version {{ chart_version }}

# runner.yaml
manifests:
- apiVersion: actions.summerwind.dev/v1alpha1
  kind: RunnerDeployment
  metadata:
    name: github-runner
  spec:
    template:
      spec:
        repository: {{ git_repo }}
        labels:
          - fast-bi-data-models
        serviceAccountName: fastbi-cicd-trigger-runner-actions-runner-controller
        resources:
          limits:
            cpu: 2500m
            memory: 8096Mi
          requests:
            cpu: 100m
            memory: 128Mi
        dockerdWithinRunnerContainer: true
        image: summerwind/actions-runner-dind
- apiVersion: actions.summerwind.dev/v1alpha1
  kind: HorizontalRunnerAutoscaler
  metadata:
    name: github-runner-hra
  spec:
    scaleTargetRef:
      name: github-runner
      # Uncomment the below in case the target is not RunnerDeployment but RunnerSet
      #kind: RunnerSet
    scaleUpTriggers:
      - githubEvent:
          workflowJob: { }
        amount: 1
        duration: "10m"
    minReplicas: 1
    maxReplicas: 10
    metrics:
      - type: PercentageRunnersBusy
        scaleUpThreshold: '0.75'
        scaleDownThreshold: '0.3'
